apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: smecqf4nb-nodejs
  janus-idp.io/tekton: smecqf4nb-nodejs
  backstage.io/kubernetes-id: smecqf4nb-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: smecqf4nb-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
