apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: smecqf4nb-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: smecqf4nb-nodejs 
  name: smecqf4nb-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: smecqf4nb-nodejs 
